name: macOS 10.14 release

on:
  push:
    tags:
      - "*"

jobs:
  build-macos-10-14:
    name: macOS 10.14 release
    runs-on: andromeda # macOS 10.14 Mojave self-hosted runner
    steps:
      - uses: actions/checkout@v2

      - name: Install and update dependencies
        run: |
          ./brew_install_or_upgrade.sh boost
          ./brew_install_or_upgrade.sh qt5
      - name: Clone conceal-core
        run: |
          rm -rf cryptonote
          git clone https://github.com/ConcealNetwork/conceal-core.git cryptonote
      - name: Build
        id: build
        run: |
          export PATH="/usr/local/opt/qt/bin:$PATH"
          build_folder="build/release"
          ccx_ver=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          release_name="ccx-desktop-macOS-10.14-v$ccx_ver"
          app_name="CONCEAL-GUI.app"
          sed -i .bk 's/HAVE_ROTR/NO_ROTR/g' CMakeLists.txt # HAVE_ROTR cheat
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -DCMAKE_C_FLAGS="-mmacosx-version-min=10.12" -DCMAKE_CXX_FLAGS="-mmacosx-version-min=10.12" -D CMAKE_BUILD_TYPE=Release ../..
          make -j4
          macdeployqt "$app_name"
          cpack
          mkdir "$release_name"
          mv *.dmg "$release_name".dmg
          zip "$release_name".zip "$release_name".dmg
          sha256=$(shasum -a 256 "$release_name".zip | awk '{ print toupper($1) }')
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=asset_path::$build_folder/$release_name.zip"
          echo "::set-output name=ccx_ver::${ccx_ver}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Conceal Desktop v${{ steps.build.outputs.ccx_ver }}
          body: |
            <img src="https://image.flaticon.com/icons/svg/25/25345.svg" width="16"> [Download for macOS 10.14](../../releases/download/${{ steps.build.outputs.ccx_ver }}/${{ steps.build.outputs.release_name }}) **${{ steps.build.outputs.release_name }}**
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
